"""empty message

Revision ID: a0a913288e9f
Revises: 092d909a74dc
Create Date: 2022-04-27 16:55:04.585641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0a913288e9f'
down_revision = '092d909a74dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('contact_user_fkey', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('shop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('url_for', sa.String(length=100), nullable=True))
        batch_op.drop_column('first_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shop', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('url_for')
        batch_op.drop_column('image_url')

    with op.batch_alter_table('contact', schema=None) as batch_op:
        batch_op.drop_constraint('contact_user_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
